### ISSUE TITLE
css_naming

### ISSUE THREAD

**Issue by yannouuuu** [Limeen/Limeen.github.io#1]
Put an "s" in the style"s".css pleaseeeeeeeeeeeeeee

The naming is important for the future of the web site

UwU `mdr```

**Comment by Limeen** [comment]
Ok!!

**Comment by Limeen** [comment]
C'est vraiment stylé 😎 😎 j'ai règlé le problème qui aurait pu causer la fin du site internet ultime, ouf..

**Comment by yannouuuu** [comment]
Bien joué Limeen ! 🥸
